export const GET_CHARACTERSLIST_START = 'GET_CHARACTERSLIST_START';
export const GET_CHARACTERSLIST_SUCCESS = 'GET_CHARACTERSLIST_SUCCESS';
export const GET_CHARACTERSLIST_FAIL = 'GET_CHARACTERSLIST_FAIL';

export const GET_CHARACTERDETAILS_START = 'GET_CHARACTERDETAILS_START';
export const GET_CHARACTERDETAILS_SUCCESS = 'GET_CHARACTERDETAILS_SUCCESS';
export const GET_CHARACTERDETAILS_FAIL = 'GET_CHARACTERDETAILS_FAIL';

export const GET_RECOMMENDATIONLIST_START = 'GET_RECOMMENDATIONLIST_START';
export const GET_RECOMMENDATIONLIST_SUCCESS = 'GET_RECOMMENDATIONLIST_SUCCESS';
export const GET_RECOMMENDATIONLIST_FAIL = 'GET_RECOMMENDATIONLIST_FAIL';